Allmatech.Teste.Web/Models/ErrorViewModel.cs
using System;

namespace Allmatech.Teste.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Allmatech.Teste.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Allmatech.Teste.Web.Models;

namespace Allmatech.Teste.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Allmatech.Teste.Web/Controllers/ImoveisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Allmatech.Teste.Model;
using Allmatech.Teste.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Allmatech.Teste.Web.Controllers
{
    public class ImoveisController : Controller
    {
        // GET: Imoveis
        public async Task<ActionResult> Index()
        {
            try
            {
                var rest = new ImoveisRest();
                var imoveis = await rest.Get();
                return View(imoveis);
            }
            catch (Exception)
            {
                return View(new List<Imovel>());
            }
        }

        // GET: Imoveis/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            try
            {
                var rest = new ImoveisRest();
                var imovel = await rest.Get(id);
                return View(imovel);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Imoveis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Imoveis/Create
        [HttpPost]
        public ActionResult Create(Imovel imovel)
        {
            try
            {
                var rest = new ImoveisRest();
                imovel.id = Guid.NewGuid();
                rest.Post(imovel);
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Imoveis/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            try
            {
                var rest = new ImoveisRest();
                var imovel = await rest.Get(id);
                return View(imovel);
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Imoveis/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, Imovel imovel)
        {
            try
            {
                var rest = new ImoveisRest();
                rest.Put(imovel);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Imoveis/Delete/5
        public ActionResult Delete(Guid id)
        {
            try
            {
                var rest = new ImoveisRest();
                rest.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Allmatech.Teste.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Allmatech.Teste.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Allmatech.Teste.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Allmatech.Teste.Web/Views/Imoveis/Create.cshtml
@model Allmatech.Teste.Model.Imovel


<h2>Imovel</h2>
<hr />

<form asp-action="Create" method="post">
    <div class="row">

        <div class="col-md-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>

        <div class="col-md-6">
            <h4>Dados do Imóvel</h4>
            <hr />
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="CodigoReferencia" class="control-label">Código Referência</label>
                        <input asp-for="CodigoReferencia" class="form-control" />
                        <span asp-validation-for="CodigoReferencia" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Descricao" class="control-label">Descrição</label>
                        <input asp-for="Descricao" class="form-control" />
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="AreaUtil" class="control-label">Área Útil</label>
                        <input asp-for="AreaUtil" class="form-control" />
                        <span asp-validation-for="AreaUtil" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="QuantidadeBanheiros" class="control-label">Banheiros</label>
                        <input asp-for="QuantidadeBanheiros" class="form-control" />
                        <span asp-validation-for="QuantidadeBanheiros" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="QuantidadeQuartos" class="control-label">Quartos</label>
                        <input asp-for="QuantidadeQuartos" class="form-control" />
                        <span asp-validation-for="QuantidadeQuartos" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <h4>Endereço</h4>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="EnderecoRua" class="control-label">Logradouro</label>
                        <input asp-for="EnderecoRua" class="form-control" />
                        <span asp-validation-for="EnderecoRua" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="EnderecoNumero" class="control-label">Número</label>
                        <input asp-for="EnderecoNumero" class="form-control" />
                        <span asp-validation-for="EnderecoNumero" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="EnderecoComplemento" class="control-label">Complemento</label>
                        <input asp-for="EnderecoComplemento" class="form-control" />
                        <span asp-validation-for="EnderecoComplemento" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EnderecoBairro" class="control-label">Bairro</label>
                        <input asp-for="EnderecoBairro" class="form-control" />
                        <span asp-validation-for="EnderecoBairro" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EnderecoCidade" class="control-label">Cidade</label>
                        <input asp-for="EnderecoCidade" class="form-control" />
                        <span asp-validation-for="EnderecoCidade" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EnderecoEstado" class="control-label">Estado</label>
                        <input asp-for="EnderecoEstado" class="form-control" />
                        <span asp-validation-for="EnderecoEstado" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="EnderecoGoogleMapsUrl" class="control-label">Google Maps Url</label>
                        <input asp-for="EnderecoGoogleMapsUrl" class="form-control" />
                        <span asp-validation-for="EnderecoGoogleMapsUrl" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h4>Anunciante</h4>
            <hr />
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="AnuncianteNome" class="control-label">Nome</label>
                        <input asp-for="AnuncianteNome" class="form-control" />
                        <span asp-validation-for="AnuncianteNome" class="text-danger"></span>
                    </div>
                    </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="AnuncianteTelefone" class="control-label">Telefone</label>
                        <input asp-for="AnuncianteTelefone" class="form-control" />
                        <span asp-validation-for="AnuncianteTelefone" class="text-danger"></span>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group text-right">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">voltar para lista</a>
</div>

Allmatech.Teste.Web/Views/Imoveis/Details.cshtml
@model Allmatech.Teste.Model.Imovel

@{
    ViewData["Title"] = "Details";
}

<h2>Imóvel</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CodigoReferencia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CodigoReferencia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AnuncianteNome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnuncianteNome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AnuncianteTelefone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnuncianteTelefone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnderecoRua)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnderecoRua)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnderecoNumero)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnderecoNumero)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnderecoComplemento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnderecoComplemento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnderecoBairro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnderecoBairro)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnderecoCidade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnderecoCidade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnderecoEstado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnderecoEstado)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EnderecoGoogleMapsUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnderecoGoogleMapsUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AreaUtil)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AreaUtil)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuantidadeBanheiros)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuantidadeBanheiros)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuantidadeQuartos)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuantidadeQuartos)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    <a asp-action="Index">Voltar para lista</a>
</div>

Allmatech.Teste.Web/Views/Imoveis/Edit.cshtml
@model Allmatech.Teste.Model.Imovel

<h2>Imóvel</h2>
<hr />

<form asp-action="Edit" method="post">
    <input asp-for="id" type="hidden"  />
    <div class="row">
        <div class="col-md-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>

        <div class="col-md-6">
            <h4>Dados do Imóvel</h4>
            <hr />
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                        <span asp-validation-for="Nome" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="CodigoReferencia" class="control-label">Código Referência</label>
                        <input asp-for="CodigoReferencia" class="form-control" />
                        <span asp-validation-for="CodigoReferencia" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Descricao" class="control-label">Descrição</label>
                        <input asp-for="Descricao" class="form-control" />
                        <span asp-validation-for="Descricao" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="AreaUtil" class="control-label">Área Útil</label>
                        <input asp-for="AreaUtil" class="form-control" />
                        <span asp-validation-for="AreaUtil" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="QuantidadeBanheiros" class="control-label">Banheiros</label>
                        <input asp-for="QuantidadeBanheiros" class="form-control" />
                        <span asp-validation-for="QuantidadeBanheiros" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="QuantidadeQuartos" class="control-label">Quartos</label>
                        <input asp-for="QuantidadeQuartos" class="form-control" />
                        <span asp-validation-for="QuantidadeQuartos" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <h4>Endereço</h4>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="EnderecoRua" class="control-label">Logradouro</label>
                        <input asp-for="EnderecoRua" class="form-control" />
                        <span asp-validation-for="EnderecoRua" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="EnderecoNumero" class="control-label">Número</label>
                        <input asp-for="EnderecoNumero" class="form-control" />
                        <span asp-validation-for="EnderecoNumero" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="EnderecoComplemento" class="control-label">Complemento</label>
                        <input asp-for="EnderecoComplemento" class="form-control" />
                        <span asp-validation-for="EnderecoComplemento" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EnderecoBairro" class="control-label">Bairro</label>
                        <input asp-for="EnderecoBairro" class="form-control" />
                        <span asp-validation-for="EnderecoBairro" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EnderecoCidade" class="control-label">Cidade</label>
                        <input asp-for="EnderecoCidade" class="form-control" />
                        <span asp-validation-for="EnderecoCidade" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EnderecoEstado" class="control-label">Estado</label>
                        <input asp-for="EnderecoEstado" class="form-control" />
                        <span asp-validation-for="EnderecoEstado" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="EnderecoGoogleMapsUrl" class="control-label">Google Maps Url</label>
                        <input asp-for="EnderecoGoogleMapsUrl" class="form-control" />
                        <span asp-validation-for="EnderecoGoogleMapsUrl" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h4>Anunciante</h4>
            <hr />
            <div class="row">
                <div class="col-md-8">
                    <div class="form-group">
                        <label asp-for="AnuncianteNome" class="control-label">Nome</label>
                        <input asp-for="AnuncianteNome" class="form-control" />
                        <span asp-validation-for="AnuncianteNome" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="AnuncianteTelefone" class="control-label">Telefone</label>
                        <input asp-for="AnuncianteTelefone" class="form-control" />
                        <span asp-validation-for="AnuncianteTelefone" class="text-danger"></span>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group text-right">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Allmatech.Teste.Web/Views/Imoveis/Index.cshtml
@model IEnumerable<Allmatech.Teste.Model.Imovel>


<h2>Imoveis</h2>
<hr />

<p class="text-right">
    <a href="@Url.Action("Create")" class="btn btn-primary">Novo Imóvel</a>
</p>

<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th width="100">Cod</th>
            <th>Nome</th>
            <th width="200" class="text-center">Ações</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3" class="text-center">ainda não há nenhum imóvel</td>
            </tr>
        }
        else
        {
            @foreach (var imovel in Model)
            {
            <tr>
                <td>@imovel.CodigoReferencia</td>
                <td>@imovel.Nome</td>
                <td class="text-center">
                    <a href="@Url.Action("Details", new { id = imovel.id })">detalhes</a> |
                    <a href="@Url.Action("Edit", new { id = imovel.id })">editar</a> |
                    <a href="@Url.Action("Delete", new { id = imovel.id })">remover</a>
                </td>
            </tr>
            }
        }
    </tbody>
</table>

Allmatech.Teste.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Allmatech.Teste.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Allmatech.Teste.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Imoveis" asp-action="Index">Imoveis</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Allmatech.Teste.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>